// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlivbjntwrdvbxoueyyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsaXZiam50d3JkdmJ4b3VleXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjE4NzUsImV4cCI6MjA3MTM5Nzg3NX0.PkTF7Qfhec2raWG0YzKInl3IBY3i3_aqyQHGCmJki8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});